Updated OMOPMeasurementLab so the joins to the temp tables include in…
SCILHS/i2o-transform pull request #13
Opened 2020-06-22 14:30 UTC by kembree1

Updated OMOPMeasurementLab so the joins to the temp tables include instance_num

2020-07-13 17:23 UTC, jklann requested changes
One typo I think...

2020-07-13 17:23 UTC, jklann commented on MSSQL/OMOPLoader.sql
> +and M.instance_num = p.instance_num
I think you mean l.instance_num?

2020-07-13 19:21 UTC, kembree1 commented on MSSQL/OMOPLoader.sql
> +and M.instance_num = p.instance_num
Yep, fixed the typo

2020-07-16 19:18 UTC, jklann commented
Add instance_num to the primary key join for measurements.

2020-07-16 19:18 UTC, merged